### ISSUE TITLE
Jivo.session.present(); not working

### ISSUE THREAD

**Issue by blackpink7** [JivoChat/JivoSDK-FlutterDemo#4]
FATAL EXCEPTION: main
                                                                                                    Process: com.jetEast.mobile.app, PID: 5772
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;
                                                                                                    	at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
                                                                                                    	at com.jivosite.sdk.databinding.FragmentJivoChatBinding.bind(FragmentJivoChatBinding.java:152)
                                                                                                    	at com.jivosite.sdk.ui.chat.JivoChatFragment.onViewCreated(JivoChatFragment.kt:90)
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034)
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952)
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:248)
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582)
                                                                                                    	at android.app.Activity.performStart(Activity.java:8628)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3807)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.databinding.DataBinderMapperImpl" on path: DexPathList[[zip file "/data/app/~~FoD9YLfOZD9q2aoTPlG6Ww==/com.jetEast.mobile.app-bNjYkdqPZHF5PRQ6hHKCrA==/base.apk"],nativeLibraryDirectories=[/data/app/~~FoD9YLfOZD9q2aoTPlG6Ww==/com.jetEast.mobile.app-bNjYkdqPZHF5PRQ6hHKCrA==/lib/arm64, /data/app/~~FoD9YLfOZD9q2aoTPlG6Ww==/com.jetEast.mobile.app-bNjYkdqPZHF5PRQ6hHKCrA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32) 
                                                                                                    	at com.jivosite.sdk.databinding.FragmentJivoChatBinding.bind(FragmentJivoChatBinding.java:152) 
                                                                                                    	at com.jivosite.sdk.ui.chat.JivoChatFragment.onViewCreated(JivoChatFragment.kt:90) 
                                                                                                    	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588) 
                                                                                                    	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272) 
                                                                                                    	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114) 
                                                                                                    	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1455) 
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3034) 
                                                                                                    	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2952) 
                                                                                                    	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263) 
                                                                                                    	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350) 
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:248) 
                                                                                                    	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1582) 
                                                                                                    	at android.app.Activity.performStart(Activity.java:8628) 
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3807) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:205) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:177) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205) 
                                                                                                    	at android.os.Looper.loop(Looper.java:294) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8177) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by tavtorkin-jivo** [comment]
@blackpink7  You should add `dataBinding = true` in **app/build.gradle**

```
android {
    ...

    buildFeatures {
        dataBinding = true
    }
}
```
